export const SLURS = [
    {
      displayText: "Aarakocra",
      options: [
        "Bird-Brains",
        "Bird-Man",
        "Caw-Caws",
        "Crow",
        "Hollowbones",
        "Parrot ",
        "Pigeon",
        "Raven",
        "Vulture"
      ],
    },
    {
      displayText: "Aasimar",
      options: [
        "Angel Face",
        "Birdy",
        "Chicken",
        "Chickenbrain",
        "God's Pet",
        "Goody Two Shoes",
        "Wingless Earthbound Bastard Half Breed"
      ],
    },
    {
      displayText: "Anyone who isn't water breathing",
      options: [
        "Drowner",
        "Landdweller",
        "Landwalker",
        "Mouth-Breather"
      ],
    },
    {
      displayText: "Centuars",
      options: [
        "Clippity-Clops",
        "Half-Horses",
        "Horse Bastards"
      ],
    },
    {
      displayText: "Dragonborns",
      options: [
        "Boot",
            "Dragon Refuse",
            "Fake-Drakes",
            "Fly Eater",
            "Forked-Tongues",
            "Gecko",
            "Iguana Wannabe",
            "Lizard",
            "Lizard Brain",
            "Lizard Wizard ",
            "Lizardfolk",
            "Man-Eater",
            "Newt",
            "Overgrown Iguana",
            "Scalebacks",
            "Scales",
            "Scalie",
            "Skinks",
            "Snakeskin",
            "Tall Kobold",
            "Walking Purse",
            "Wyrm Reject",
            "Wyrm Wannabe"
      ],
    },
    {
      displayText: "Drow",
      options: [
        "Ash-Face",
        "Cavemen",
        "Chimney Sweep",
        "Dirt Elves",
        "Dwarven Imposter",
        "Filth-Skin",
        "Moss Licker",
        "Murker",
        "Spider Kisser",
        "Tall Dwarfs",
        "Underscum"
      ],
    },
    {
      displayText: "Dwarves",
      options: [
        "Angry Footstool",
            "Beard-Goblin",
            "Bushies",
            "Cave Hippo",
            "Copper Polisher",
            "Dirt Farie",
            "Dirt-Licker",
            "Flea-Bearded Alestain",
            "Giant Snot",
            "Gnomes",
            "Gold Digger",
            "Gut Draggers",
            "Gutter Rats",
            "Hairy Brewery",
            "Hairy Halfling",
            "Half-Man",
            "Half-Sized Alcoholic",
            "Hammer Midget",
            "Hill Farie",
            "Keg Belly",
            "Knoties",
            "Lumberfoot",
            "Maggots ",
            "Mountain Farie",
            "Oremonger",
            "Pubic Face",
            "Pump Sucker",
            "Pyrite-Muncher",
            "Rock Biter",
            "Rock Eater",
            "Rockhead",
            "Spuds",
            "Squash ",
            "Stone Domes",
            "Stone Humper",
            "Stone Sh*tter",
            "Stunt",
            "Stunty",
            "Teapot",
            "Tunnel Rat"
      ],
    },
    {
      displayText: "Elves",
      options: [
        "Arrogant Stuck Up Tree Fondling Hippies",
            "Bark Sniffer",
            "Beardless",
            "Bird Boned",
            "Butterboys",
            "Chinfolk",
            "Daggar Head",
            "Daisy Sniffer",
            "Dandelion Eater",
            "Dew Drinker",
            "Discount Dryad",
            "Drow (except to actual drow)",
            "Fairy Folk",
            "Faithless Woodland Sprite",
            "Fancy Lad",
            "Farie Wannabes",
            "Fey Mongrols",
            "Keeb",
            "Knife-Ears",
            "Leaf Lickers",
            "Leafblower",
            "Left Handed Casters",
            "Light Weights",
            "Mushroom Dancers",
            "Oozebait ",
            "Pixie",
            "Pointy",
            "Pointy Ears",
            "Pole-Proportioned Dendrophile",
            "Rabbit",
            "Sharp Ears",
            "Tinkerbell",
            "Tree F*cker",
            "Tree Hugger",
            "Tree-Thumpers",
            "Waste of Immortality",
            "Wedgie (they're uptight)",
            "Weed Eater",
            "Wingless Farie",
            "Wood-Heads"
      ],
    },
    {
      displayText: "Genasi (Air)",
      options: [
        "Airhead",
            "Leaf Blower",
            "Spark Plug",
            "Unfavorable Fart ",
            "Windbags"
      ],
    },
    {
      displayText: "Genasi (Earth)",
      options: [
        "Gravel Bed",
            "Rock-for-Brains",
            "Sedimentary",
            "Slabs",
            "Stone Sucker"
      ],
    },
    {
      displayText: "Genasi (Fire)",
      options: [
        "Cold Heart",
        "Hazard",
        "Hothead",
        "Flameface",
        "Matchstick",
        "Sunburn"
      ],
    },
    {
      displayText: "Giants",
      options: [
        "Nesthair ",
        "Tumbletower "
      ],
    },
    {
      displayText: "Gnoll",
      options: [
        "Carrion-Eaters",
        "Cur",
        "Dog",
        "Hunger Slave",
        "Mutt"
      ],
    },
    {
      displayText: "Gnoll",
      options: [
        "Carrion-Eaters",
        "Cur",
        "Dog",
        "Hunger Slave",
        "Mutt"
      ],
    },
    {
      displayText: "Gnomes",
      options: [
        "Ankle Biter",
        "Bug-Eyed Stumps",
        "Cone Head",
        "Discount Dwarf",
        "Dwarflings",
        "Fat Fairy",
        "Glamer-Slingers",
        "Halfling",
        "KneeLicker",
        "Lawn Darts",
        "Lawn Ornaments",
        "Mini-Elf",
        "Mushroom Sucker",
        "Quarterling",
        "Shaved Hobgoblin",
        "Sniffers",
        "Tinkertots",
        "Trickster"
      ],
    },
    {
      displayText: "Goblins",
      options: [
        "Gobber",
        "Greenskin",
        "Orcslave",
        "Slimeskin",
        "Toothpick-Nose",
        "Trash Gnome"
      ],
    },
    {
      displayText: "Half-Elves (from elves)",
      options: [
        "Bastards",
        "Half Bad",
        "Half Breed",
        "Halfie",
        "Mayfly Babies",
        "Mongrels",
        "Moodbloods"
      ],
    },
    {
      displayText: "Half-Elves (from humans)",
      options: [
        "Fling Kids",
        "Half Good",
        "Halfways",
        "Mules",
        "Mutts",
        "Not Enough",
        "Traitor Babies"
      ],
    },
    {
      displayText: "Halflings",
      options: [
        "All-You-Can-Eat",
        "Ankle Biter",
        "Arm Rest",
        "Bilbo",
        "Children",
        "Dire-Midged",
        "Dwarfling",
        "Fairy Giant",
        "Gnome",
        "Hairless Dwarf",
        "Hairy Doorstop",
        "Half Men",
        "Hill Goblin",
        "Hobbit",
        "Leatherfoot",
        "Runt",
        "Shaved Dwarf",
        "Shin Licker",
        "Small Fry",
        "Sneakies",
        "Sticky Fingers",
        "Succling",
        "Swine"
      ],
    },
    {
      displayText: "Humans",
      options: [
        "Cattle",
        "Dire Halfling",
        "Doubling (from halflings)",
        "Dust",
        "Full-Lings",
        "Generic Protag #435 (if a PC)",
        "Graceless Elf",
        "Joe Bloggs",
        "Humie",
        "Lumberfoot",
        "Mayfly",
        "Milkskins (from orcs)",
        "Monkey",
        "Monkeys",
        "Morties",
        "Normie",
        "Pig Skin",
        "Pink Thing",
        "Pink-Skin",
        "Pinks",
        "Quisling ",
        "Rabbit Spawn ",
        "Round Ears",
        "Roundteeth",
        "Short-Life",
        "Shortlived",
        "Smoothskin",
        "Soft One (from lizardfolk)",
        "Spoon-Ears",
        "Succling",
        "Swine",
        "Tree-Killers (from elves)",
        "Whore-Race (they're the reason for half breeds)",
        "World-Blight (from elves)"
      ],
    },
    {
      displayText: "Indirect Racial Slurs",
      options: [
        "A bag of leftovers from a restaurant: \"<em>An Orc-y Bag</em>\"",
            "A dagger: \"<em>A Gnomish Greatsword</em>\"",
            "Bad breath: \"<em>Dragonborn Singing</em>\"",
            "Barrels of whiskey: \"<em>Dwarven Wetnurse</em>\"",
            "Happy endings at a massage parlor: \"<em>Human Style</em>\"",
            "Laying a dwarf or gnome: \"<em>Boulder Rolling</em>\"",
            "Picking a lock: \"<em>Banging a Halfling's Sister</em>\"",
            "Pickpocketing: \"<em>Halfing Handshake</em>\"",
            "Public drunkenness: \"<em>Going Dwarven</em>\"",
            "Stealing a horse: \"<em>Taking a Half-Orc Bride</em>\"",
            "The act of going barefoot: \"<em>Wearing Halfling Shoes</em>\" (some stores have signs forbidding halfling shoes)",
            "The bastard children of non-human races: \"<em>Half-Man</em>\"",
            "Unshaven men: \"<em>Dwarf Babies</em>\"",
            "Vegetables: \"<em>Elf Food</em>\"",
            "Whiskey: \"<em>Dwarf Milk</em>\""
      ],
    },
    {
      displayText: "Kenku",
      options: [
        "Caw-Caws",
            "Copycats",
            "Crow",
            "Flightless",
            "Hollowbones",
            "Jabbers",
            "Mockingbirds",
            "Noisemakers",
            "Parrot (in tropical/port cities)",
            "Peckers",
            "Raven"
      ],
    },
    {
      displayText: "Orcs / Half-Orcs",
      options: [
        "Broccoli Head",
        "Dorc",
        "Dire Goblin",
        "Forc",
        "Green Ape",
        "Greenskins",
        "Gronk",
        "Grunt",
        "Halfbreed",
        "Halfie",
        "Lumberfoot",
        "Necro-Breath",
        "Ogre Droppings",
        "Orcy McOrcface",
        "Pig-Face",
        "Savages",
        "Scumbreed",
        "Slimeskin",
        "Swampskin",
        "The Green Beast ",
        "Tusk-Face",
        "Tuskers"
      ],
    },
    {
      displayText: "Tabaxi",
      options: [
        "Cat",
        "Dog Lover",
        "Fleabag",
        "Hairball",
        "Milk Drinker",
        "Milk Lapper",
        "Worm Farm"
      ],
    },
    {
      displayText: "Tieflings",
      options: [
        "Brighteyes",
        "Bullheads",
        "Clip-Clops",
        "Demon Child",
        "Demon Wannabe",
        "Devil Bastard",
        "Devil Spawn",
        "Failbirth",
        "Filth",
        "Freak",
        "Gargoyles",
        "Goat Face",
        "Half-Hells",
        "Handle Heads",
        "Hell-Touched",
        "Hellspawn",
        "Pox",
        "Sideshow",
        "Tainted Ones",
        "Tall Imps",
        "Unbirth",
        "Unloveables "
      ],
    },
    {
      displayText: "Tortle",
      options: [
        "Dome Head",
        "Shellhead",
        "Shell-less",
        "Slowpoke"
      ],
    },
    {
      displayText: "Triton",
      options: [
        "Coral Eater",
        "Dolphin Born",
        "Fish F*cker",
        "Wet Blanket"
      ],
    },
    {
      displayText: "Warforged",
      options: [
        "Clinking Clanking Clattering Collection of Caliginous Junk",
        "Dolls",
        "Dumbells",
        "Dummies (as in training/target dummy)",
        "Fakes / Facsimiles",
        "Gear Head",
        "Golem (they're living constructs)",
        "Golems",
        "Hunk of Junk",
        "Lemon",
        "Made-to-Orders",
        "Marionettes / Puppets",
        "Robot",
        "Rust Bucket",
        "Rusties",
        "Scarecrows",
        "Scrap Heap",
        "Walking Casket",
        "Walking Talking Tools"
      ],
    },
  ];